test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID: YOUR_CREDENTIAL_HERE
  PAYPAL_CLIENT_SECRET: YOUR_CREDENTIAL_HERE
  STRIPE_PUBLISHABLE_KEY:	pk_test_51N4pHBSAgwv12TvKxg5bW9ld8hr88UkRCMrL17Lb8Pn4svXvV6S8CZqYb7j0c7v154A8WvQStqlqt08ARP4Z63xX00nOQBxwxM
  STRIPE_SECRET_KEY: 	sk_test_51N4pHBSAgwv12TvKUo66dl6P8wJhVzIeUU9XxAkmtZvzChqRdS9ERIL0up5AbFPuyS4dwPHBVh9BohKhTtNeKM2P00SwSmmU1S
development:
  <<: *default